services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
        REACT_APP_AUTH_URL: ${REACT_APP_AUTH_URL:-http://localhost:8547}
    container_name: flagsapp-local
    ports:
      - "3001:80"
    networks:
      - backend-flags
      - openid_network

networks:
  backend-flags:
    external: true
  openid_network:
    external: true
