services:
  app:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-https://localhost:3001}
        REACT_APP_AUTH_URL: ${REACT_APP_AUTH_URL:-https://localhost:8547}
    container_name: flagsapp-local
    ports:
      - "3001:80"
    networks:
      - backend-flags
      - openid_network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://localhost:3001}
      - REACT_APP_AUTH_URL=${REACT_APP_AUTH_URL:-https://localhost:8547}

networks:
  backend-flags:
    external: true
  openid_network:
    external: true
